### PR TITLE
This is 1/2 of SC-10

### PR DESCRIPTION
**Pull request by buckyoung**
This will play a child ship exiting "animation" when you interact with the child ship module.

I call it an "animation" because the player cannot control the ship during this time (but it is not a proper animation).

Furthermore, I began implementing the system where the other player must help you get back aboard (but it is not finished yet)... as such you cannot disengage with the child ship module after you get in the child ship. This is expected.

---

I was able to do some nifty things with coroutines in order to yield execution flow back to unity's internal game loop while we wait for the "animation" to play. Check out the code when you get a second!

### CODE REVIEW

**Comment by buckyoung** [comment]
Dropping these here for reference 

---

img_0214

---

img_0215

**Comment by buckyoung** [comment]
Note: 1-3 are implemented. 4-6 will be implemented asap

**Comment by buckyoung** [comment]
http://www.gfycat.com/BreakableShabbyAmericanmarten

**Comment by nathandonato** [comment]
This is sick.

**Pull request merged**
